#!/bin/sh /opt/etc/init.d/COMMAND
# AWG init script for Entware
# Auto-generated by xkeen-ui
# Start/stop all AmneziaWG interfaces

START=90
STOP=10

AWG_QUICK=/opt/bin/awg-quick
CONFIG_DIR=/opt/etc/awg

get_confs() {
  ls "$CONFIG_DIR"/*.conf 2>/dev/null | while read -r f; do
    basename "$f" .conf
  done
}

start() {
  for iface in $(get_confs); do
    echo "Starting AWG interface: $iface"
    "$AWG_QUICK" up "$iface" 2>&1
  done
}

stop() {
  for iface in $(get_confs); do
    echo "Stopping AWG interface: $iface"
    "$AWG_QUICK" down "$iface" 2>&1
  done
}

restart() {
  stop
  start
}

status() {
  for iface in $(get_confs); do
    if ip link show "$iface" >/dev/null 2>&1; then
      echo "$iface: up"
    else
      echo "$iface: down"
    fi
  done
}

case "$1" in
  start) start ;;
  stop) stop ;;
  restart) restart ;;
  status) status ;;
  *) echo "Usage: $0 {start|stop|restart|status}"; exit 1 ;;
esac
