#!/bin/sh
# AWG init script for Entware
# Auto-generated by xkeen-ui
# Manages all AmneziaWG interfaces with role-aware firewall rules.
#
# - Client configs (WARP): awg-quick up/down + fwmark routing for Xray
# - Server configs (home access): awg-quick up/down + iptables INPUT/FORWARD/NAT
#
# The 'check' command restores iptables for active servers (for cron watchdog).

START=90
STOP=10

AWG_QUICK=/opt/bin/awg-quick
AWG=/opt/bin/awg
CONFIG_DIR=/opt/etc/awg
XKEEN_UI=/opt/bin/xkeen-ui

# --- Interface detection ---
detect_wan_iface() {
  ip route show default 2>/dev/null | sed -n 's/.*dev \([^ ]*\).*/\1/p' | head -1
}

detect_lan_iface() {
  for iface in br0 bridge br-lan; do
    if ip link show "$iface" >/dev/null 2>&1; then
      echo "$iface"
      return
    fi
  done
  echo "br0"
}

WAN_IFACE=$(detect_wan_iface)
[ -z "$WAN_IFACE" ] && WAN_IFACE=eth3
LAN_IFACE=$(detect_lan_iface)

# --- Config helpers ---
get_confs() {
  ls "$CONFIG_DIR"/*.conf 2>/dev/null | while read -r f; do
    basename "$f" .conf
  done
}

# Returns "server" if config has ListenPort in [Interface] and no Endpoint in [Peer]
get_role() {
  conf="$CONFIG_DIR/$1.conf"
  has_listen=0
  has_endpoint=0
  in_peer=0
  [ -f "$conf" ] || { echo "client"; return; }
  while IFS= read -r line; do
    line=$(echo "$line" | tr -d ' \r')
    case "$line" in
      \[*) in_peer=0; [ "$line" = "[Peer]" ] && in_peer=1 ;;
      ListenPort=*) has_listen=1 ;;
      Endpoint=*) [ "$in_peer" = "1" ] && has_endpoint=1 ;;
    esac
  done < "$conf"
  if [ "$has_listen" = "1" ] && [ "$has_endpoint" = "0" ]; then
    echo "server"
  else
    echo "client"
  fi
}

get_listen_port() {
  conf="$CONFIG_DIR/$1.conf"
  grep -i "^ListenPort" "$conf" 2>/dev/null | head -1 | sed 's/.*= *//;s/[^0-9]//g'
}

get_tunnel_subnet() {
  conf="$CONFIG_DIR/$1.conf"
  # Try to get from first peer AllowedIPs
  ip=$(grep -A999 '^\[Peer\]' "$conf" 2>/dev/null | grep -i 'AllowedIPs' | head -1 | sed 's/.*= *//' | cut -d, -f1 | tr -d ' ')
  ip=$(echo "$ip" | cut -d/ -f1)
  oct1=$(echo "$ip" | cut -d. -f1)
  oct2=$(echo "$ip" | cut -d. -f2)
  oct3=$(echo "$ip" | cut -d. -f3)
  if [ -n "$oct1" ] && [ -n "$oct2" ] && [ -n "$oct3" ]; then
    echo "${oct1}.${oct2}.${oct3}.0/24"
    return
  fi
  # Fallback: derive from Interface Address
  addr=$(grep -i '^Address' "$conf" | head -1 | sed 's/.*= *//' | cut -d, -f1 | tr -d ' ' | cut -d/ -f1)
  oct1=$(echo "$addr" | cut -d. -f1)
  oct2=$(echo "$addr" | cut -d. -f2)
  oct3=$(echo "$addr" | cut -d. -f3)
  if [ -n "$oct1" ] && [ -n "$oct2" ] && [ -n "$oct3" ]; then
    echo "${oct1}.${oct2}.${oct3}.0/24"
    return
  fi
  echo "10.8.0.0/24"
}

# --- Firewall management ---
# is_firewall_applied returns 0 (true) if the INPUT rule for this port
# already exists, preventing duplicate rules on repeated start/check calls.
is_firewall_applied() {
  port="$1"
  iptables -C INPUT -p udp --dport "$port" -j ACCEPT 2>/dev/null
}

apply_server_firewall() {
  iface="$1"
  port=$(get_listen_port "$iface")
  [ -z "$port" ] && port=443
  subnet=$(get_tunnel_subnet "$iface")

  # Idempotent: skip if firewall rules already in place
  if is_firewall_applied "$port"; then
    echo "  Firewall already applied: port=$port subnet=$subnet"
    return
  fi

  echo "  Applying firewall: port=$port subnet=$subnet lan=$LAN_IFACE wan=$WAN_IFACE"
  iptables -I INPUT -p udp --dport "$port" -j ACCEPT 2>/dev/null
  iptables -I FORWARD -i "$iface" -o "$LAN_IFACE" -j ACCEPT 2>/dev/null
  iptables -I FORWARD -i "$LAN_IFACE" -o "$iface" -j ACCEPT 2>/dev/null
  iptables -I FORWARD -i "$iface" -o "$WAN_IFACE" -j ACCEPT 2>/dev/null
  iptables -I FORWARD -i "$WAN_IFACE" -o "$iface" -j ACCEPT 2>/dev/null
  iptables -t nat -A POSTROUTING -s "$subnet" -j MASQUERADE 2>/dev/null
  ip route add "$subnet" dev "$iface" 2>/dev/null
}

remove_server_firewall() {
  iface="$1"
  port=$(get_listen_port "$iface")
  [ -z "$port" ] && port=443
  subnet=$(get_tunnel_subnet "$iface")
  echo "  Removing firewall: port=$port subnet=$subnet"
  ip route del "$subnet" dev "$iface" 2>/dev/null
  iptables -t nat -D POSTROUTING -s "$subnet" -j MASQUERADE 2>/dev/null
  iptables -D FORWARD -i "$WAN_IFACE" -o "$iface" -j ACCEPT 2>/dev/null
  iptables -D FORWARD -i "$iface" -o "$WAN_IFACE" -j ACCEPT 2>/dev/null
  iptables -D FORWARD -i "$LAN_IFACE" -o "$iface" -j ACCEPT 2>/dev/null
  iptables -D FORWARD -i "$iface" -o "$LAN_IFACE" -j ACCEPT 2>/dev/null
  iptables -D INPUT -p udp --dport "$port" -j ACCEPT 2>/dev/null
}

# --- Lifecycle ---
start() {
  for iface in $(get_confs); do
    role=$(get_role "$iface")
    # Idempotent: skip interfaces that are already up
    if ip link show "$iface" >/dev/null 2>&1; then
      echo "AWG interface $iface ($role) already up, skipping"
      # Ensure firewall is in place (safe — apply_server_firewall is idempotent)
      if [ "$role" = "server" ]; then
        apply_server_firewall "$iface"
      fi
      continue
    fi
    echo "Starting AWG interface: $iface ($role)"
    "$AWG_QUICK" up "$CONFIG_DIR/$iface.conf" 2>&1
    if [ "$role" = "server" ]; then
      apply_server_firewall "$iface"
    fi
  done
}

stop() {
  for iface in $(get_confs); do
    role=$(get_role "$iface")
    echo "Stopping AWG interface: $iface ($role)"
    if [ "$role" = "server" ]; then
      remove_server_firewall "$iface"
    fi
    "$AWG_QUICK" down "$CONFIG_DIR/$iface.conf" 2>&1
  done
}

restart() {
  stop
  start
}

status() {
  for iface in $(get_confs); do
    role=$(get_role "$iface")
    if ip link show "$iface" >/dev/null 2>&1; then
      echo "$iface: up ($role)"
    else
      echo "$iface: down ($role)"
    fi
  done
}

# check: restore firewall rules for active server interfaces (for cron watchdog).
# Idempotent: apply_server_firewall skips if rules already present.
check() {
  for iface in $(get_confs); do
    role=$(get_role "$iface")
    if [ "$role" = "server" ] && ip link show "$iface" >/dev/null 2>&1; then
      apply_server_firewall "$iface"
    fi
  done
}

case "$1" in
  start) start ;;
  stop) stop ;;
  restart) restart ;;
  status) status ;;
  check) check ;;
  *) echo "Usage: $0 {start|stop|restart|status|check}"; exit 1 ;;
esac
